"use client";
import NavBar from "@/components/NavBar";
import { AuthProvider } from "@/context/authContext";
import "./globals.css";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {" "}
        <AuthProvider>
          {" "}
          <NavBar />
          {children}{" "}
        </AuthProvider>
      </body>
    </html>
  );
}
