"use client";
import NavBar from "@/components/NavBar";
import { AuthProvider } from "@/context/authContext";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Auth0Provider } from "@auth0/auth0-react";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {" "}
        <AuthProvider>
          {/* <Auth0Provider
            domain="dev-y7sfhgw3mwbhd7lm.us.auth0.com"
            clientId="NOBU9MH4a4Ptz6yzDDGHBDKFKMU89Ltf"
            authorizationParams={{
              redirect_uri: window.location.origin,
            }}
          > */}
          <NavBar />
          <ToastContainer />
          {children} {/* </Auth0Provider>{" "} */}
        </AuthProvider>
      </body>
    </html>
  );
}
